version: 2

web:
  name: omni-chat-app
  type: web
  startCommand: npm start
  env:
    - key: JWT_SECRET
      value: "Am0fZr5mEta2KihNo0dU0ua2Re1Dle05"
    - key: MONGODB_URI
      value: "mongodb+srv://curtisweenie:free-119@seg.sbyvxq7.mongodb.net/chatapp?retryWrites=true&w=majority&appName=SEG"
    - key: FACEBOOK_VERIFY_TOKEN
      value: "my-free-app-1234"
    - key: PORT
      value: "3000"
  buildCommand: "npm install"
  healthCheckPath: "/api/facebook/test-webhook"
  allowInsecureHealthChecks: true
  autoDeploy: true
